print_log= true
log_file= "output.log"
database= "talmobil"
database_ip= "mongodb://localhost:27017/"
timeout= 2
file_home= "home.html"
file_add_car= "add-car.html"
file_calendar= "calendar.html"
file_car_edit= "edit-car.html"
file_car_services= "car-services.html"
file_car_overview= "car-overview.html"
file_car_view= "car-view.html"
file_drive= "drive.html"
file_locations= "locations.html"